name: MakeCode Arcade Release

on: 
  release:
    types:
      - created
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache npm and makecode
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.pxt/mkc-cache
          key: ${{ runner.os }}
      - name: npm install
        run: |
          npm install -g makecode
      - name: build
        run: |
          makecode --hw f4
          mv built/binary.uf2 built/f4.uf2
          makecode --hw d5
          mv built/binary.uf2 built/d5.uf2
          cat built/*.uf2 > drop.uf2
        env:
          CI: true
      - name: upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./drop.uf2
          asset_name: combined-f4-d5.uf2
          asset_content_type: application/octet-stream
